# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Огурец_3",
  "description": "Лучшие огурещ на рынке_3"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/4/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные огурки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помидо&o=id
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "www.ленинград-спб1",
  "positions": [
    {
      "product": 3,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 4,
      "quantity": 10,
      "price": 80
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/17/
Content-Type: application/json

{
    "positions": [
    {
      "product": 4,
      "quantity": 100000,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 1000,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=5
Content-Type: application/json


